# basic mcbot on github ill try to add my own proxies :)

name: nullping with mcbot on github.

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      my_value:
        description: 'ip of server'
        required: true
        default: 'foo'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          git clone https://github.com/nejason57mars/mcbot.git
          cd mcbot
          rm -rf proxies.txt
          wget https://openproxylist.xyz/socks4.txt
          mv socks4.txt proxies.txt
          java -jar MCBOT.jar {{ github.event.inputs.my_value }} 340 botjoiner 500 -1
